'use client';

import { useEffect, useState } from 'react';
import { CalendarDays, CheckCircle2, Clock3, LockKeyhole } from 'lucide-react';
import { createClient } from '@/lib/supabase';

type Day = { id: string; day_number: number; title: string; scheduled_date: string; start_time: string; end_time: string; duration_minutes: number };

export function ExamSchedule() {
  const [days, setDays] = useState<Day[]>([]);
  const [completed, setCompleted] = useState<string[]>([]);
  const [message, setMessage] = useState('');
  useEffect(() => { const load = async () => { const client = createClient(); const { data: exam } = await client.from('exams').select('id').eq('code', 'CET-2026').eq('is_published', true).maybeSingle(); if (!exam) return; const { data: dayRows } = await client.from('exam_days').select('id,day_number,title,scheduled_date,start_time,end_time,duration_minutes').eq('exam_id', exam.id).eq('is_published', true).order('day_number'); setDays(dayRows ?? []); const { data: { user } } = await client.auth.getUser(); if (user) { const { data: application } = await client.from('applications').select('id').eq('user_id', user.id).maybeSingle(); if (application) { const { data: attempts } = await client.from('exam_attempts').select('exam_day_id,status').eq('application_id', application.id).eq('exam_id', exam.id); setCompleted((attempts ?? []).filter((attempt: { status: string }) => ['submitted', 'completed', 'expired'].includes(attempt.status)).map((attempt: { exam_day_id: string }) => attempt.exam_day_id)); } } }; void load(); }, []);
  const today = new Date().toISOString().slice(0, 10);
  return <section className="border border-slate-300 bg-card p-6"><div className="flex items-start justify-between gap-4"><div><p className="font-mono text-[10px] uppercase tracking-[0.2em] text-primary">Linux CS Entrance Examination 2026</p><h2 className="mt-1 font-serif text-2xl font-bold">Six-day examination schedule</h2><p className="mt-2 text-sm text-muted-foreground">Only the published day scheduled for today can be started.</p></div><CalendarDays className="text-primary" /></div>{message && <p className="mt-4 border border-amber-200 bg-amber-50 p-3 text-sm text-amber-800">{message}</p>}<div className="mt-5 grid gap-3">{days.map((day) => { const isCompleted = completed.includes(day.id); const available = day.scheduled_date === today && !isCompleted; const past = day.scheduled_date < today; return <article key={day.id} className="flex flex-col gap-4 border border-slate-200 p-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-start gap-3">{isCompleted ? <CheckCircle2 className="mt-1 text-emerald-600" size={20} /> : available ? <Clock3 className="mt-1 text-primary" size={20} /> : <LockKeyhole className="mt-1 text-slate-400" size={20} />}<div><p className="text-xs font-semibold uppercase tracking-wider text-slate-400">Day {day.day_number}</p><h3 className="font-semibold">{day.title}</h3><p className="mt-1 text-sm text-muted-foreground">{new Date(`${day.scheduled_date}T00:00:00`).toLocaleDateString('en-IN')} · {day.start_time.slice(0, 5)}–{day.end_time.slice(0, 5)} · {day.duration_minutes} minutes</p></div></div>{isCompleted ? <span className="text-sm font-semibold text-emerald-700">Completed</span> : available ? <button onClick={() => setMessage('The examination attempt interface will open when this day is started from the published exam workflow.')} className="bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground">Start Examination</button> : <span className="text-sm font-semibold text-slate-500">{past ? 'Unavailable' : 'Upcoming'}</span>}</article>; })}</div></section>;
}
