'use client'

import { useEffect, useState } from 'react'
import { createClient } from '@/lib/supabase'

type Props = { applicationId: string }
type ScoreCard = { id?: string; subjects: { name: string; max: number; obtained: number }[]; total_marks: number; obtained_marks: number; percentage: number; grade: string; result: string; status: 'draft' | 'published' }

const initial: ScoreCard = { subjects: [], total_marks: 0, obtained_marks: 0, percentage: 0, grade: '', result: '', status: 'draft' }

export function ScoreCardAdminPanel({ applicationId }: Props) {
  const [score, setScore] = useState<ScoreCard>(initial)
  const [subject, setSubject] = useState({ name: '', max: '100', obtained: '0' })
  const [message, setMessage] = useState('')
  useEffect(() => { const load = async () => { const { data } = await createClient().from('score_cards').select('*').eq('application_id', applicationId).maybeSingle(); if (data) setScore(data) }; void load() }, [applicationId])
  const addSubject = () => { if (!subject.name.trim()) return; const next = [...score.subjects, { name: subject.name.trim(), max: Number(subject.max) || 0, obtained: Number(subject.obtained) || 0 }]; const total = next.reduce((sum, item) => sum + item.max, 0); const obtained = next.reduce((sum, item) => sum + item.obtained, 0); const percentage = total ? Number(((obtained / total) * 100).toFixed(2)) : 0; setScore({ ...score, subjects: next, total_marks: total, obtained_marks: obtained, percentage, grade: percentage >= 90 ? 'A+' : percentage >= 80 ? 'A' : percentage >= 70 ? 'B' : percentage >= 60 ? 'C' : percentage >= 40 ? 'D' : 'F', result: percentage >= 40 ? 'PASS' : 'FAIL' }); setSubject({ name: '', max: '100', obtained: '0' }) }
  const save = async (status: 'draft' | 'published') => { const payload = { ...score, application_id: applicationId, status, published_at: status === 'published' ? new Date().toISOString() : null, updated_at: new Date().toISOString() }; const { data, error } = await createClient().from('score_cards').upsert(payload, { onConflict: 'application_id' }).select('*').single(); if (error) setMessage(error.message); else { setScore(data); setMessage(status === 'published' ? 'Score Card published.' : 'Score Card saved as draft.') } }
  return <section className="border-t p-6" aria-labelledby="score-card-heading"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs uppercase tracking-wide text-slate-500">Student result</p><h2 id="score-card-heading" className="text-lg font-semibold text-[#092f52]">Score Card Management</h2></div><span className="text-xs font-semibold uppercase text-slate-500">{score.status}</span></div><div className="mt-4 grid gap-2 sm:grid-cols-[1fr_120px_120px_auto]"><input className="border p-2 text-sm" placeholder="Subject" value={subject.name} onChange={(e) => setSubject({ ...subject, name: e.target.value })} /><input className="border p-2 text-sm" type="number" placeholder="Max" value={subject.max} onChange={(e) => setSubject({ ...subject, max: e.target.value })} /><input className="border p-2 text-sm" type="number" placeholder="Obtained" value={subject.obtained} onChange={(e) => setSubject({ ...subject, obtained: e.target.value })} /><button onClick={addSubject} className="bg-slate-800 px-3 py-2 text-sm font-semibold text-white">Add</button></div><div className="mt-3 flex flex-wrap gap-2 text-sm">{score.subjects.map((item, index) => <span key={`${item.name}-${index}`} className="border px-3 py-1">{item.name}: {item.obtained}/{item.max}</span>)}</div><div className="mt-4 grid gap-3 sm:grid-cols-3"><label className="text-sm">Grade<input className="mt-1 w-full border p-2" value={score.grade} onChange={(e) => setScore({ ...score, grade: e.target.value })} /></label><label className="text-sm">Result<input className="mt-1 w-full border p-2" value={score.result} onChange={(e) => setScore({ ...score, result: e.target.value })} /></label><div className="text-sm"><span className="block">Summary</span><strong className="mt-2 block text-lg">{score.obtained_marks}/{score.total_marks} · {score.percentage}%</strong></div></div><div className="mt-4 flex flex-wrap gap-2"><button onClick={() => save('draft')} className="border border-slate-300 px-4 py-2 text-sm font-semibold">Save draft</button><button onClick={() => save('published')} className="bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground">Publish Score Card</button></div>{message && <p className="mt-3 text-sm text-slate-600">{message}</p>}</section>
}
