'use client'

import Link from 'next/link'
import { useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import { createClient } from '@/lib/supabase/client'
import type { Exam } from '@/lib/exam'

export default function ExamDashboardPage() {
  const router = useRouter(); const [exams, setExams] = useState<Exam[]>([]); const [name, setName] = useState('Student'); const [loading, setLoading] = useState(true)
  useEffect(() => { (async () => { const supabase = createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) { router.replace('/exam/login'); return } setName(user.user_metadata?.full_name || user.email?.split('@')[0] || 'Student'); const { data } = await supabase.from('exams').select('id,title,code,description,duration_minutes,total_marks,passing_marks,starts_at,ends_at').order('starts_at', { ascending: true }); setExams((data || []) as Exam[]); setLoading(false) })() }, [router])
  return <main className="space-y-6"><div className="flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-blue-700">Student examination portal</p><h1 className="mt-1 text-3xl font-bold text-slate-900">Good morning, {name}</h1><p className="mt-1 text-sm text-slate-500">Select an available examination to continue.</p></div><button onClick={() => createClient().auth.signOut().then(() => router.replace('/exam/login'))} className="self-start rounded-lg border border-slate-300 px-4 py-2 text-sm font-semibold text-slate-700">Sign out</button></div>{loading ? <div className="rounded-xl bg-white p-8 text-sm text-slate-500">Loading examinations…</div> : exams.length === 0 ? <div className="rounded-xl border border-amber-200 bg-amber-50 p-8"><h2 className="font-semibold text-amber-950">No examination is currently available</h2><p className="mt-1 text-sm text-amber-900">Published examinations will appear here when the examination cell releases them.</p></div> : <div className="grid gap-4 md:grid-cols-2">{exams.map(exam => <article key={exam.id} className="rounded-xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-wider text-blue-700">{exam.code}</p><h2 className="mt-1 text-xl font-bold text-slate-900">{exam.title}</h2></div><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-semibold text-emerald-800">Available</span></div><p className="mt-3 text-sm leading-6 text-slate-600">{exam.description || 'Computer-based examination administered by the State Common Entrance Test Cell.'}</p><div className="mt-5 flex gap-5 border-t border-slate-100 pt-4 text-sm text-slate-600"><span>{exam.duration_minutes} minutes</span><span>{exam.total_marks} marks</span></div><Link href={`/exam/${exam.id}/instructions`} className="mt-5 block rounded-lg bg-blue-800 px-4 py-3 text-center text-sm font-semibold text-white hover:bg-blue-900">View instructions</Link></article>)}</div>}</main>
}
