'use client'

import { useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import { createClient } from '@/lib/supabase/client'

export default function VerificationPage() {
  const router = useRouter(); const [candidate, setCandidate] = useState<Record<string, string | null> | null>(null); const [loading, setLoading] = useState(true)
  useEffect(() => { (async () => { const supabase = createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) return router.replace('/student/login'); const { data: app } = await supabase.from('applications').select('id,application_number,personal_data').eq('user_id', user.id).maybeSingle(); if (!app) return router.replace('/student/login'); const { data: ticket } = await supabase.from('hall_ticket_details').select('candidate_name,application_number,roll_number,exam_name,exam_date,exam_time,exam_center_name,photo_path').eq('application_id', app.id).maybeSingle(); const personal = (app.personal_data || {}) as Record<string, string>; setCandidate({ name: ticket?.candidate_name || personal.full_name || null, application: ticket?.application_number || app.application_number, roll: ticket?.roll_number || null, exam: ticket?.exam_name || 'Linux CS Entrance Examination', date: ticket?.exam_date || null, session: ticket?.exam_time || null, center: ticket?.exam_center_name || null }); setLoading(false) })() }, [router]); if (loading) return <main className="p-10 text-center text-slate-500">Loading candidate verification…</main>; if (!candidate) return null; return <main className="min-h-[calc(100vh-8rem)] bg-[#f4f7fb] px-6 py-12"><section className="mx-auto max-w-3xl rounded-3xl border border-[#d8e4ed] bg-white p-8 shadow-xl shadow-[#123b5d]/5"><p className="text-xs font-bold uppercase tracking-[0.22em] text-[#287a78]">Secure identity check</p><h1 className="mt-2 text-3xl font-bold text-[#123b5d]">Candidate Verification</h1><div className="mt-8 grid gap-5 sm:grid-cols-2">{Object.entries({ 'Candidate Name': candidate.name, 'Application Number': candidate.application, 'Roll Number': candidate.roll, Examination: candidate.exam, 'Exam Center': candidate.center, 'Exam Date': candidate.date, Session: candidate.session }).map(([label, value]) => <div key={label} className="rounded-xl bg-[#f4f7fb] p-4"><p className="text-xs font-bold uppercase tracking-wide text-slate-500">{label}</p><p className="mt-2 font-semibold text-[#123b5d]">{value || 'Not available'}</p></div>)}</div><button onClick={() => router.push('/student/examination/instructions')} className="mt-8 w-full rounded-xl bg-[#287a78] px-5 py-3.5 font-bold text-white hover:bg-[#216462]">Continue to Instructions</button></section></main>
}
